version: '3.8'

services:
  app:
    build: .        
    ports:
      - "8080:8080"               
    env_file:
      - .env                      
    depends_on:
      - db                         

  db:
    image: postgres:latest         
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: newpassword 
      POSTGRES_DB: music_db        
    ports:
      - "5432:5432"               
